<?php
/**
 * Loom Theme Shell - Functions
 *
 * This is the WordPress theme entry point.
 * It bootstraps Loom Core and loads the developer's theme module.
 *
 * DO NOT EDIT THIS FILE.
 * Configure your theme in config/themes/your-theme/
 *
 * @package Loom\ThemeShell
 */



// Ensure Loom Core is active
if (!defined('LOOM_CORE_VERSION')) {
    add_action('admin_notices', function () {
        echo '<div class="error"><p><strong>Loom Theme Shell</strong> requires the Loom Core plugin to be activated.</p></div>';
    });
    return;
}

// Define theme paths
if (!defined('LOOM_THEME_PATH')) {
    define('LOOM_THEME_PATH', get_stylesheet_directory() . '/');
}

// Get active theme from option or use 'default'
$themeConfig = get_option('loom_active_theme', 'default');

// Look for developer theme in multiple locations
$themePaths = [
    // Project root config (D:\project-loom\config\themes\{theme}\)
    dirname(WP_CONTENT_DIR) . "/config/themes/{$themeConfig}/",
    // wp-content config
    WP_CONTENT_DIR . "/config/themes/{$themeConfig}/",
    // Themes directory
    WP_CONTENT_DIR . "/themes/loom-{$themeConfig}/",
];

$themeLoaded = false;

foreach ($themePaths as $themePath) {
    if (is_dir($themePath) && file_exists($themePath . 'theme.php')) {
        require_once $themePath . 'theme.php';
        $themeLoaded = true;

        // Define the loaded theme path
        if (!defined('LOOM_DEVELOPER_THEME_PATH')) {
            define('LOOM_DEVELOPER_THEME_PATH', $themePath);
        }
        break;
    }
}

// Load default/fallback theme if no developer theme found
if (!$themeLoaded) {
    require_once __DIR__ . '/default-theme.php';
}

// Register theme support
add_action('after_setup_theme', function () {
    // Standard WordPress theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', [
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ]);
    add_theme_support('custom-logo');
    add_theme_support('customize-selective-refresh-widgets');
    add_theme_support('responsive-embeds');
    add_theme_support('align-wide');

    // WooCommerce support
    add_theme_support('woocommerce');
    add_theme_support('wc-product-gallery-zoom');
    add_theme_support('wc-product-gallery-lightbox');
    add_theme_support('wc-product-gallery-slider');

    // Navigation menus
    register_nav_menus([
        'primary' => __('Primary Menu', 'loom'),
        'secondary' => __('Secondary Menu', 'loom'),
        'footer' => __('Footer Menu', 'loom'),
    ]);

    // Content width
    if (!isset($content_width)) {
        $GLOBALS['content_width'] = 1200;
    }
});

// Register widget areas
add_action('widgets_init', function () {
    register_sidebar([
        'name' => __('Sidebar', 'loom'),
        'id' => 'sidebar-1',
        'description' => __('Add widgets here to appear in your sidebar.', 'loom'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget' => '</section>',
        'before_title' => '<h2 class="widget-title">',
        'after_title' => '</h2>',
    ]);

    register_sidebar([
        'name' => __('Footer', 'loom'),
        'id' => 'footer-1',
        'description' => __('Add widgets here to appear in your footer.', 'loom'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title">',
        'after_title' => '</h3>',
    ]);
});
